development:
  adapter: postgresql
  encoding: unicode
  database: melendez_development
  pool: 5
  username: chevy
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: melendez_test
  pool: 5
  username: chevy
  password: 123456

production:
  adapter: postgresql
  encoding: unicode
  database: melendez_production
  pool: 5
  username: chevy
  password: 123456
